-- =============================================================================
-- Removes everything supabase/seed/demo-shows-calendar.sql (demo-calendar-2026-10) added:
-- the six calendar shows and every row hanging off them (classes, entries,
-- orders, stalls, waivers, staff, ledger rows, add-ons, vendor items).
-- GENERATED by scripts/generate-demo-calendar-seed.mjs — regenerate rather than edit.
-- The main demo dataset (riders, horses, other shows) is untouched.
--
-- class_entries DELETE is guarded (canEditShow), so this acts as the org's
-- Organizer for the transaction (request.jwt.claims, transaction-local).
-- =============================================================================
begin;

do $$
declare
  actor uuid;
begin
  select u.id into actor from public.users u
   where u.platform_role = 'Organizer' and u.org_id = 'a0000000-0000-4000-8000-000000000004'
   order by u.created_at limit 1;
  if actor is null then
    select u.id into actor from public.users u where u.platform_role = 'SuperAdmin' order by u.created_at limit 1;
  end if;
  if actor is null then
    raise exception 'No Organizer or SuperAdmin user to act as';
  end if;
  perform set_config('request.jwt.claims', json_build_object('sub', actor, 'role', 'authenticated')::text, true);
end $$;

create temp table _cal_show_ids (id uuid primary key) on commit drop;
insert into _cal_show_ids values
  ('f38106d9-dc18-4195-a57b-efebea1edf99'),
  ('d21b06c6-1315-44af-968f-c2c98b4d2ca3'),
  ('2cb46297-13a1-48d2-ad88-7dfa32ba0cce'),
  ('9ae451a8-67e0-4460-ba72-34b7177c2815'),
  ('aaa77721-4b0b-4147-85b5-ce6bfb0c917d'),
  ('8fd739a4-a494-46c9-b153-035a211b9221');

delete from public.class_entries
 where class_id in (select id from public.classes where show_id in (select id from _cal_show_ids));
delete from public.stabling_requests where show_id in (select id from _cal_show_ids);
-- orders -> shows is ON DELETE RESTRICT, so orders go before the shows.
delete from public.orders where show_id in (select id from _cal_show_ids);
delete from public.shows where id in (select id from _cal_show_ids);

commit;
