-- Read-only state of the date-relative show calendar (demo-calendar-2026-10).
-- GENERATED by scripts/generate-demo-calendar-seed.mjs. Safe to run any time.
--
--   scripts/apply-demo-seed.sh --calendar-verify
--
-- Ticket window is evaluated like riders/utils/parse-ticket-window.ts: opens at
-- ticket_open 00:00 show-local, closes at ticket_close (23:59 when no time) or
-- the end of the last show day, whichever is first. Stage is the dashboard's
-- (listDashboardShows): complete > live (runner.approved) > sales-closed
-- (runner.ticketClosed) > sales-open (published) > setup.
with cal as (
  select s.*, coalesce(s.timezone, 'America/New_York') as tz
  from public.shows s
  where s.id in ('f38106d9-dc18-4195-a57b-efebea1edf99', 'd21b06c6-1315-44af-968f-c2c98b4d2ca3', '2cb46297-13a1-48d2-ad88-7dfa32ba0cce', '9ae451a8-67e0-4460-ba72-34b7177c2815', 'aaa77721-4b0b-4147-85b5-ce6bfb0c917d', '8fd739a4-a494-46c9-b153-035a211b9221')
),
win as (
  select c.id,
         (c.ticket_open::date)::timestamp at time zone c.tz as opens_at,
         least(
           (left(c.ticket_close, 10)::date + coalesce(nullif(substring(c.ticket_close from '(\d{2}:\d{2})'), ''), '23:59')::time) at time zone c.tz,
           (c.end_date::date + time '23:59:59') at time zone c.tz
         ) as closes_at
  from cal c
),
stats as (
  select c.id,
         (select count(*) from public.orders o where o.show_id = c.id and o.status = 'paid') as orders,
         (select coalesce(sum(o.amount_total), 0) from public.orders o where o.show_id = c.id and o.status = 'paid') as gross,
         (select count(*) from public.class_entries ce join public.classes k on k.id = ce.class_id where k.show_id = c.id) as entries,
         (select count(distinct ce.rider_id) from public.class_entries ce join public.classes k on k.id = ce.class_id where k.show_id = c.id) as riders,
         (select count(*) from public.classes k where k.show_id = c.id) as classes,
         (select count(*) from public.classes k where k.show_id = c.id and k.catalog_id is not null) as linked,
         (select count(*) from public.classes k where k.show_id = c.id and k.date = to_char((now() at time zone c.tz)::date, 'YYYY-MM-DD')) as today_classes,
         (select count(*) from public.classes k where k.show_id = c.id and k.time is not null) as timed,
         (select coalesce(sum(sr.horse_stalls), 0) from public.stabling_requests sr where sr.show_id = c.id) as stalls,
         (select count(*) from public.staff_assignments sa where sa.show_id = c.id) as staff,
         (select min(ce.num) || '–' || max(ce.num) from public.class_entries ce join public.classes k on k.id = ce.class_id where k.show_id = c.id) as nums,
         case when exists (select 1 from public.classes k where k.show_id = c.id and k.results_published) then 'complete'
              when (c.runner_state ->> 'approved')::boolean then 'live'
              when (c.runner_state ->> 'ticketClosed')::boolean then 'sales-closed'
              when c.published then 'sales-open' else 'setup' end as stage
  from cal c
)
select metric, value from (
  select 0 as ord, 'today (America/New_York)' as metric, to_char((now() at time zone 'America/New_York')::date, 'YYYY-MM-DD Dy') as value
  union all
  select row_number() over (order by c.start_date)::int,
         c.name,
         c.start_date || case when c.end_date <> c.start_date then ' → ' || c.end_date else '' end
         || ' | tickets ' || case when now() < w.opens_at then 'OPENS ' || c.ticket_open
                                  when now() > w.closes_at then 'CLOSED ' || left(c.ticket_close, 10)
                                  else 'OPEN until ' || to_char(w.closes_at at time zone c.tz, 'YYYY-MM-DD HH24:MI') end
         || ' | stage ' || st.stage
         || ' | ' || st.orders || ' orders $' || st.gross || ', ' || st.entries || ' entries, ' || st.riders || ' riders'
         || coalesce(' #' || st.nums, '')
         || ' | ' || st.classes || ' classes (' || st.linked || ' catalog-linked, ' || st.timed || ' timed, ' || st.today_classes || ' today)'
         || ' | ' || st.stalls || ' stalls, ' || st.staff || ' staff'
  from cal c join win w on w.id = c.id join stats st on st.id = c.id
  union all
  select 100, 'CHECK orders total <> sum(items)',
         (select count(*) from public.orders o where o.show_id in ('f38106d9-dc18-4195-a57b-efebea1edf99', 'd21b06c6-1315-44af-968f-c2c98b4d2ca3', '2cb46297-13a1-48d2-ad88-7dfa32ba0cce', '9ae451a8-67e0-4460-ba72-34b7177c2815', 'aaa77721-4b0b-4147-85b5-ce6bfb0c917d', '8fd739a4-a494-46c9-b153-035a211b9221') and o.amount_total <> (select coalesce(sum((e ->> 'amount')::numeric), 0) from jsonb_array_elements(o.items) e))::text
  union all
  select 101, 'CHECK orders items <> class entries',
         (select count(*) from public.orders o where o.show_id in ('f38106d9-dc18-4195-a57b-efebea1edf99', 'd21b06c6-1315-44af-968f-c2c98b4d2ca3', '2cb46297-13a1-48d2-ad88-7dfa32ba0cce', '9ae451a8-67e0-4460-ba72-34b7177c2815', 'aaa77721-4b0b-4147-85b5-ce6bfb0c917d', '8fd739a4-a494-46c9-b153-035a211b9221') and (select count(*) from jsonb_array_elements(o.items) e where e ->> 'kind' = 'class_entry') <> (select count(*) from public.class_entries ce where ce.order_id = o.id))::text
  union all
  select 102, 'CHECK orders outside window / future',
         (select count(*) from public.orders o join public.shows s on s.id = o.show_id
           where s.id in ('f38106d9-dc18-4195-a57b-efebea1edf99', 'd21b06c6-1315-44af-968f-c2c98b4d2ca3', '2cb46297-13a1-48d2-ad88-7dfa32ba0cce', '9ae451a8-67e0-4460-ba72-34b7177c2815', 'aaa77721-4b0b-4147-85b5-ce6bfb0c917d', '8fd739a4-a494-46c9-b153-035a211b9221')
             and (o.paid_at > now() or (o.paid_at at time zone 'America/New_York')::date < s.ticket_open::date
                  or (o.paid_at at time zone 'America/New_York')::date > left(s.ticket_close, 10)::date))::text
  union all
  select 103, 'CHECK duplicate rider numbers per class',
         (select count(*) from (select ce.class_id, ce.num from public.class_entries ce join public.classes k on k.id = ce.class_id
                                 where k.show_id in ('f38106d9-dc18-4195-a57b-efebea1edf99', 'd21b06c6-1315-44af-968f-c2c98b4d2ca3', '2cb46297-13a1-48d2-ad88-7dfa32ba0cce', '9ae451a8-67e0-4460-ba72-34b7177c2815', 'aaa77721-4b0b-4147-85b5-ce6bfb0c917d', '8fd739a4-a494-46c9-b153-035a211b9221') group by 1, 2 having count(*) > 1) x)::text
) m
order by ord;
