-- Bridle numbers stop being auto-generated by count and become assigned
-- from an organizer-defined pool of the physical numbers the show office
-- actually has (one or more ranges, individual numbers markable
-- unavailable). Entry/back number generation is untouched — this only
-- changes the primary horse ("bridle") number.

-- A horse can now exist before its bridle number is assigned ("waiting").
-- The existing unique index already treats multiple NULLs as distinct, so
-- no index change is needed for that.
alter table public.show_horses alter column bridle_number drop not null;

-- Organizer-facing pack metadata (e.g. "201-500", label "Pack A").
create table public.show_number_ranges (
  id uuid primary key default gen_random_uuid(),
  show_id uuid not null references public.shows (id) on delete cascade,
  range_start integer not null,
  range_end integer not null check (range_end >= range_start),
  label text,
  created_at timestamptz not null default now(),
  created_by uuid references public.users (id)
);

-- One materialized row per possible number across every range for a show.
-- Populated by createNumberRange() via `insert ... on conflict do nothing`
-- so overlapping packs dedupe automatically. status drives both the
-- "next available" claim query and the office status dashboard.
create table public.show_bridle_numbers (
  id uuid primary key default gen_random_uuid(),
  show_id uuid not null references public.shows (id) on delete cascade,
  number integer not null,
  status text not null default 'available'
    check (status in ('available', 'assigned', 'unavailable')),
  show_horse_id uuid references public.show_horses (id) on delete set null,
  source_range_id uuid references public.show_number_ranges (id) on delete cascade,
  unavailable_reason text,
  created_at timestamptz not null default now()
);
create unique index show_bridle_numbers_unique_idx on public.show_bridle_numbers (show_id, number);
create index show_bridle_numbers_status_idx on public.show_bridle_numbers (show_id, status);

-- Audit trail for corrections ("replace a lost number").
create table public.bridle_number_changes (
  id uuid primary key default gen_random_uuid(),
  show_id uuid not null references public.shows (id) on delete cascade,
  show_horse_id uuid not null references public.show_horses (id) on delete cascade,
  old_number text,
  new_number text,
  reason text,
  changed_by uuid references public.users (id),
  changed_at timestamptz not null default now()
);

alter table public.show_number_ranges enable row level security;
alter table public.show_bridle_numbers enable row level security;
alter table public.bridle_number_changes enable row level security;

create policy show_number_ranges_select on public.show_number_ranges for select using (public.can_view_show(show_id));
create policy show_number_ranges_write on public.show_number_ranges for all
  using (public.has_show_permission(show_id, 'canManageEntryLedger'))
  with check (public.has_show_permission(show_id, 'canManageEntryLedger'));

create policy show_bridle_numbers_select on public.show_bridle_numbers for select using (public.can_view_show(show_id));
create policy show_bridle_numbers_write on public.show_bridle_numbers for all
  using (public.has_show_permission(show_id, 'canManageEntryLedger'))
  with check (public.has_show_permission(show_id, 'canManageEntryLedger'));

-- Audit trail is office-only, not general staff viewing.
create policy bridle_number_changes_select on public.bridle_number_changes for select
  using (public.has_show_permission(show_id, 'canManageEntryLedger'));
create policy bridle_number_changes_write on public.bridle_number_changes for all
  using (public.has_show_permission(show_id, 'canManageEntryLedger'))
  with check (public.has_show_permission(show_id, 'canManageEntryLedger'));
